# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Installing my packages
        run: cd www && npm install

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: "latest"

      - name: Build my App
        run: npm run build && wasm-pack build --target web && cp index_to_build.html pkg/index.html && touch ./pkg/.nojekyll

      - name: Add debug
        run: ls pkg -f && rm pkg/.gitignore

      - name: Add .gitignore to avoid send github workflow
        run: echo '.github' >> .gitignore

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: pkg # The folder the action should deploy.

      - run: 'curl -i -H ''Accept: application/json'' -H ''Content-Type:application/json'' -X POST --data ''{"content":"Deploy da aplicação *wasm-city*","title":"Deploy finalizado"}'' https://discord.com/api/webhooks/${{ secrets.DISCORD_KEY }}'
